#!/bin/bash
# =============================================================================
# scripts/ca-bootstrap/01-enroll-bootstrap-admin.sh
# =============================================================================
# Step 1 of the RWRRN crypto-material bootstrap sequence.
#
# WHAT THIS DOES:
#   Enrolls the Fabric CA's built-in bootstrap identity (admin:adminpw, set
#   via `fabric-ca-server start -b admin:adminpw` in docker-compose.yml) as a
#   Fabric CA *client* identity. This produces a local MSP folder (cert +
#   private key) that lets us talk to the CA as an authenticated admin for
#   all subsequent `fabric-ca-client register` calls (Step 2 onward).
#
# WHAT THIS DOES NOT DO:
#   - It does NOT create the orderer/peer/org-admin identities yet (Step 2+).
#   - It does NOT touch docker-compose.yml or restart any container.
#   - It is idempotent: if the bootstrap admin's MSP already exists, it exits
#     without re-enrolling (re-enrolling would silently issue a *new*
#     certificate and is a deliberate, separate action, not a side effect of
#     re-running this script).
#
# HOW TO RUN (manually, via SSH on the VPS, NOT via the deploy workflow):
#   cd /opt/rwrrn
#   cp .env.template .env        # first time only, then fill in real secrets
#   docker compose exec cli bash
#   cd /opt/gopath/src/github.com/hyperledger/fabric/peer
#   bash scripts/ca-bootstrap/01-enroll-bootstrap-admin.sh
#
# PREREQUISITE:
#   The .env file must exist in the repo root (mounted into cli at
#   /opt/gopath/src/github.com/hyperledger/fabric/peer/.env via the existing
#   `../scripts:/opt/gopath/.../scripts` bind — see note at bottom on the one
#   extra mount you need to add).
# =============================================================================

set -euo pipefail

# --- Load configuration ------------------------------------------------------
ENV_FILE="${ENV_FILE:-/opt/gopath/src/github.com/hyperledger/fabric/peer/.env}"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: .env not found at $ENV_FILE"
  echo "Copy .env.template to .env in the repo root on the VPS and fill in values first."
  exit 1
fi
set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

: "${ORG_CODE:?ORG_CODE not set in .env}"
: "${CA_NAME:?CA_NAME not set in .env}"
: "${CA_HOST:?CA_HOST not set in .env}"
: "${CA_PORT:?CA_PORT not set in .env}"
: "${CA_BOOTSTRAP_USER:?CA_BOOTSTRAP_USER not set in .env}"
: "${CA_BOOTSTRAP_PASS:?CA_BOOTSTRAP_PASS not set in .env}"

# --- Paths --------------------------------------------------------------------
FABRIC_CA_CLIENT_HOME="/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ca-clients/${ORG_CODE}/bootstrap-admin"
CA_TLS_CERT="/opt/gopath/src/github.com/hyperledger/fabric/peer/fabric-ca/${ORG_CODE}/tls-cert.pem"

echo "== Step 1: Enroll CA bootstrap admin (${CA_BOOTSTRAP_USER}) =="
echo "CA:          https://${CA_HOST}:${CA_PORT} (name: ${CA_NAME})"
echo "Client home: ${FABRIC_CA_CLIENT_HOME}"

# --- Idempotency check --------------------------------------------------------
if [[ -d "${FABRIC_CA_CLIENT_HOME}/msp/signcerts" ]] && \
   [[ -n "$(ls -A "${FABRIC_CA_CLIENT_HOME}/msp/signcerts" 2>/dev/null)" ]]; then
  echo "Bootstrap admin already enrolled at ${FABRIC_CA_CLIENT_HOME}/msp — skipping."
  echo "(Delete that folder manually first if you intentionally want to re-enroll.)"
  exit 0
fi

# --- Sanity check: is the CA's TLS cert reachable from inside this container?
if [[ ! -f "$CA_TLS_CERT" ]]; then
  echo "ERROR: CA TLS cert not found at $CA_TLS_CERT"
  echo "This file is generated by the CA on first start and lives on the VPS at"
  echo "  /opt/rwrrn/fabric-ca/${ORG_CODE}/tls-cert.pem"
  echo "Check that docker-compose.yml mounts ./fabric-ca/${ORG_CODE} into the cli"
  echo "container too (it currently only mounts it into the CA service)."
  exit 1
fi

mkdir -p "${FABRIC_CA_CLIENT_HOME}"
export FABRIC_CA_CLIENT_HOME

# --- Enroll --------------------------------------------------------------------
fabric-ca-client enroll \
  -u "https://${CA_BOOTSTRAP_USER}:${CA_BOOTSTRAP_PASS}@${CA_HOST}:${CA_PORT}" \
  --caname "${CA_NAME}" \
  --tls.certfiles "${CA_TLS_CERT}"

echo ""
echo "== Done =="
echo "Bootstrap admin enrolled. MSP written to:"
echo "  ${FABRIC_CA_CLIENT_HOME}/msp"
echo ""
echo "Next step (Step 2): register the real org admin identity, then register"
echo "and enroll orderer0/orderer1/peer0/peer1. Do NOT proceed automatically —"
echo "confirm this step's output first."
